// Therdweb
const THIRDWEB_AUTH_DOMAIN = process.env.NEXT_PUBLIC_THIRDWEB_AUTH_DOMAIN ?? '';
const THIRDWEB_AUTH_CLIENT_ID = process.env.THIRDWEB_AUTH_CLIENT_ID ?? '';
const THIRDWEB_AUTH_PRIVATE_KEY = process.env.THIRDWEB_AUTH_PRIVATE_KEY ?? '';

export const env = {
  THIRDWEB_AUTH_DOMAIN,
  THIRDWEB_AUTH_CLIENT_ID,
  THIRDWEB_AUTH_PRIVATE_KEY,
};
