import { ReactNode } from 'react';
import { Providers } from './providers/Providers';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="ja">
      <Providers>
        <body>{children}</body>
      </Providers>
    </html>
  );
}
