import './globals.css';
import { ReactNode } from 'react';
import { Providers } from './_features/providers/Providers';
import { Noto_Sans_JP } from '@next/font/google';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

const notoSansJP400 = Noto_Sans_JP({
  weight: '400',
  display: 'swap',
  preload: false,
});
const notoSansJP700 = Noto_Sans_JP({
  weight: '700',
  display: 'swap',
  preload: false,
});

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="ja">
      <Providers>
        <body
          style={{
            fontFamily: 'Noto Sans JP, sans-serif',
          }}
        >
          {children}
        </body>
      </Providers>
    </html>
  );
}
