name: CI

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Bun
        run: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Run ESLint
        run: bunx eslint ./app --ext .js,.jsx,.ts,.tsx
        continue-on-error: true
